name: CI

on:
  pull_request:
    paths-ignore:
    - releases/**
  push:
    branches:
    - main
    paths-ignore:
    - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo build
        gh workflow run release.yaml -f environment=development
      env:
        GH_TOKEN: ${{ github.token }}
