name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo deploy "$ENVIRONMENT"
        echo version "$(cat releases/$ENVIRONMENT/version)"
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GH_TOKEN: ${{ github.token }}
