name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }} ## only one deploy at a time please
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo deploy version "$(cat releases/"$ENVIRONMENT"/version)" "$ENVIRONMENT"
        echo version "$(cat releases/"$ENVIRONMENT"/version)"
      env:
        ENVIRONMENT: ${{ inputs.environment }}
