name: Trigger deploy on production version change

on:
  push:
    branches:
    - main
    paths:
      - 'releases/production/version'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        gh workflow run deployment.yaml -f environment="$ENVIRONMENT"
      env:
        ENVIRONMENT: production
        GH_TOKEN: ${{ github.token }}
