name: Trigger deploy on test version change

on:
  push:
    branches:
    - main
    paths:
      - 'releases/test/version'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        gh workflow run deployment.yaml -f environment="$ENVIRONMENT"
      env:
        ENVIRONMENT: test
        GH_TOKEN: ${{ github.token }}
